import { ProxyHost, Certificate } from 'shared';
import * as fs from 'fs';
import * as path from 'path';
import { getCertificateById } from '../database';

const NGINX_CONFIG_DIR = '/etc/nginx/sites-enabled';
const NGINX_CONFIG_FILE = path.join(NGINX_CONFIG_DIR, 'proxy-manager.conf');

export const generateNginxConfig = (hosts: ProxyHost[], certificates: Certificate[] = []): string => {
  const enabledHosts = hosts.filter(h => h.enabled);
  const certMap = new Map(certificates.map(c => [c.id, c]));

  const serverBlocks = enabledHosts.map(host => {
    let sslConfig = '';
    
    if (host.sslEnabled && host.certificateId) {
      const cert = certMap.get(host.certificateId);
      if (cert) {
        sslConfig = `
    ssl_certificate ${cert.certPath};
    ssl_certificate_key ${cert.keyPath};
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;`;
      }
    }

    return `
server {
    listen 80;
    listen [::]:80;
    server_name ${host.domain};

    location / {
        proxy_pass ${host.targetUrl};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }${
      host.sslEnabled && sslConfig ? `
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name ${host.domain};${sslConfig}
    location / {
        proxy_pass ${host.targetUrl};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }` : ''
    }`;
  }).join('\n');

  return `# Auto-generated by Proxy Manager
${serverBlocks}
`;
};

export const writeNginxConfig = (hosts: ProxyHost[], certificates: Certificate[] = []): void => {
  const config = generateNginxConfig(hosts, certificates);
  fs.writeFileSync(NGINX_CONFIG_FILE, config);
};

export const reloadNginx = (): void => {
  try {
    require('child_process').execSync('nginx -s reload', { stdio: 'ignore' });
  } catch (e) {
    console.log('Nginx reload called (may not be running in dev mode)');
  }
};
